# Generated by Django 5.1.7 on 2025-04-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stataus',
            new_name='status',
        ),
    ]
